# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbarena
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veilarbarena/internal/isAlive
    initialDelay: 120
  readiness:
    path: veilarbarena/internal/selftest
    initialDelay: 120
prometheus:
  enabled: true
  path: veilarbarena/internal/metrics
resources:
  limits:
    cpu: 3
fasitResources:
  used:
  # custom veilarbarena props
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: loadbalancer:veilarbarena
    resourceType: loadbalancerconfig
  - alias: srvveilarbarena
    resourceType: credential

  # stolen resources
  - alias: veilarbportefoljeDB
    resourceType: datasource

  # security resources
  - alias: isso-rp-user
    resourceType: credential
  - alias: isso-host
    resourceType: baseUrl
  - alias: isso-jwks
    resourceType: baseUrl
  - alias: isso-issuer
    resourceType: baseUrl
  - alias: isso.isalive
    resourceType: baseUrl
  - alias: veilarblogin.redirect-url
    resourceType: baseUrl

  # SOAP-services
  - alias: Aktoer_v2
    resourceType: webserviceendpoint
  - alias: Oppfoelgingsstatus_v1
    resourceType: webserviceendpoint

  exposed:
  - alias: veilarbarenaAPI
    resourceType: restservice
    path: /veilarbarena/api
team: oppfolging
