kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbarena
  namespace: {{namespace}}
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbarena/veilarbarena:{{version}}
  ingresses:
    - https://veilarbarena-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarbarena
  liveness:
    path: veilarbarena/internal/isAlive
    port: 8080
    initialDelay: 120
  port: 8080
  prometheus:
    enabled: true
    path: veilarbarena/internal/metrics
  readiness:
    path: veilarbarena/internal/isReady
    port: 8080
    initialDelay: 120
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      memory: 512Mi
  webproxy: true
  leaderElection: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbarena
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/dev/creds/veilarbarena_{{namespace}}-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/preprod/fss/veilarbarena/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
