kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbarena
  namespace: default
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbarena/veilarbarena:{{version}}
  ingresses:
    - https://veilarbarena.nais.adeo.no
  port: 8080
  prometheus:
    enabled: true
    path: veilarbarena/internal/metrics
  readiness:
    path: veilarbarena/internal/isReady
    initialDelay: 30
  liveness:
    path: veilarbarena/internal/isAlive
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  webproxy: true
  leaderElection: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarbarena
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/prod/creds/veilarbarena-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/prod/fss/veilarbarena/default
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
